{{- if and .Values.prometheus (eq .Values.prometheus.enabled true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emailsender.fullname" . }}-prometheus
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    {{- include "emailsender.prometheusLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      {{- include "emailsender.prometheusSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "emailsender.prometheusSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time={{ .Values.prometheus.retention }}'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--web.enable-lifecycle'
          ports:
            - name: http
              containerPort: {{ .Values.prometheus.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: storage
              mountPath: /prometheus
          resources:
          {{- toYaml .Values.prometheus.resources | nindent 10 }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: {{ include "emailsender.fullname" . }}-prometheus-config
        - name: storage
          emptyDir: {}
{{- end }}
