apiVersion: v1
kind: Service
metadata:
  name: emailsender
spec:
  type: {{ .Values.service.type }}
  selector:
    app: emailsender
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9091
