{{- if and .Values.serviceMonitor (eq .Values.serviceMonitor.enabled true) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "emailsender.fullname" . }}
  namespace: kubectl port-forward -n monitoring svc/monitoring-kube-prometheus-prometheus 9090:9090
{{ .Values.app.namespace }}
  labels:
    {{- include "emailsender.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "emailsender.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
