apiVersion: v1
kind: Service
metadata:
  name: emailsender
  namespace: default
  labels:
    app.kubernetes.io/name: emailsender
    app.kubernetes.io/instance: emailsender
spec:
  type: {{ .Values.service.type }}
  selector:
    app: emailsender
  ports:
    - name: http
      port: 9091
      targetPort: 9091
