{{- if and .Values.serviceMonitor (eq .Values.serviceMonitor.enabled true) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "emailsender.fullname" . }}
  namespace: monitoring
  labels:
    release: monitoring
    {{- include "emailsender.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.app.namespace }}
  selector:
    matchLabels:
      {{- include "emailsender.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
