replicaCount: 2

app:
  name: emailsender
  namespace: default

image:
  repository: shakhzodjon/emailsender
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9091

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 30s
  scrapeTimeout: 10s

prometheus:
  enabled: false
  namespace: monitoring
  replicaCount: 1
  retention: 7d
  image:
    repository: prom/prometheus
    tag: v2.52.0
    pullPolicy: IfNotPresent
  service:
    port: 9090
    targetPort: 9090
    type: ClusterIP
  scrapeInterval: 15s
  scrapeTimeout: 10s
  resources: {}

